apiVersion: v1
kind: PersistentVolume
metadata:
  name: vpro-db-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
     path: "/mnt/data"
