apiVersion: v1
kind: PersistentVolume
metadata:
  name: vpro-db-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /docker_volume/
    server: 10.0.0.117
    readOnly: false
