kind: PersistentVolume
apiVersion: v1
metadata:
  name: vpro-db-data
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-068451097f4f7cf62
    fsType: ext4
