---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vpro-db-data
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://us-east-1f/vol-068451097f4f7cf62
  capacity:
    storage: 3Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
