apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: vprocache01
  name: vprocache01
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vprocache01
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: vprocache01
    spec:
      containers:
        - image: memcached
          name: vprocache01
          ports:
            - containerPort: 11211
          resources: {}
      restartPolicy: Always
status: {}
