apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: vproapp
  name: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vproapp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: vproapp
    spec:
      containers:
        - image: anmolkushwaha/vprofileapp:V1
          name: vproapp
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/tomcat/webapps
              name: vproappdata
      restartPolicy: Always
      volumes:
        - name: vproappdata
          persistentVolumeClaim:
            claimName: vproappdata
status: {}
